[package]
name = "qn-changelog-rs"
version = "0.1.0"
authors = ["Wang Xuerui <wangxuerui@qiniu.com>"]

[dependencies]
docopt = "0.8"
github-rs = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
