[package]
name = "qn-changelog-rs"
version = "0.1.0"
authors = ["Wang Xuerui <wangxuerui@qiniu.com>"]

[profile.release]
lto = true

[dependencies]
atomicwrites = "0.1"
chrono = "0.4"
docopt = "0.8"
error-chain = "0.11"
# github-rs = "0.6"
lazy_static = "1.0"
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.github-rs]
git = "https://github.com/xen0n/github-rs"
branch = "temp-for-qn-changelog"
default-features = false
features = ["rust-native-tls"]
